MyType   {
  #region ThisIsMyRegion

  #horizontal

  #vertical

  num: Int = 1
  str: String = ""
  fl1: Float32 = 1.0
  fl2: Float64 = 0.0
  arr: Float32[10]
  boo: Bool = false

  MyType  {
    #region ThisIsMyRegion

    #horizontal

    #vertical

    num: Int = 1
    str: String = ""
    fl1: Float32 = 1.0
    fl2: Float64 = 0.0
    arr: Float32[10]
    boo: Bool = false

    MyType  {
      #region ThisIsMyRegion

      #horizontal

      #vertical

      num: Int = 1
      str: String = ""
      fl1: Float32 = 1.0
      fl2: Float64
      arr: Float32[10]
      boo: Bool = false
    }
  }
}
