Type {

  //foo1: Int
  //foo2: Int[]
  //foo3: Int[10]
  //foo4: Unit
  //foo5: ()
  //foo6: (asd: Int)
  //foo7: Int -> Int
  //foo8: Int[] -> Int[]
  //foo9: (f: Int[10]) -> (arr: Int[10])
  //foo10: String

}

main Int -> Int {
  
  //foo: Int = 0
  //return
  //return 0
  //return foo
  //bar $
}
